@@include('scripts/ibg.js')
@@include('scripts/menu.js')
@@include('scripts/welcome.js')
@@include('scripts/explore.js')
@@include('scripts/video.js')
@@include('scripts/gallery.js')
@@include('scripts/ticket.js')